const GETALLCOUNTRIES = 'GETALLCOUNTRIES';
const GETCOUNTRYBYID = 'GETCOUNTRYBYID';
const CLEAN_COUNTRY = 'CLEAN_COUNTRY';
const GETACTIVITIES = 'GETACTIVITIES';
const CREATE_ACTIVITY = 'CREATE_ACTIVITY';


export { GETALLCOUNTRIES, GETCOUNTRYBYID, CLEAN_COUNTRY, GETACTIVITIES, CREATE_ACTIVITY }

