const GET_ALL_COUNTRIES = 'GETALLCOUNTRIES';
const GET_COUNTRY_BY_ID = 'GETCOUNTRYBYID';
const CLEAN_COUNTRY = 'CLEAN_COUNTRY';
const GET_ACTIVITIES = 'GETACTIVITIES';
const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
const SORT_BY_NAME = 'SORT_BY_NAME';
const SORT_BY_POPULATION = 'SORT_BY_POPULATION';
const SEARCH_BY_NAME = 'SEARCH_BY_NAME'


export { GET_ALL_COUNTRIES, GET_COUNTRY_BY_ID, CLEAN_COUNTRY, GET_ACTIVITIES, CREATE_ACTIVITY, FILTER_BY_CONTINENT, SORT_BY_NAME, SORT_BY_POPULATION, SEARCH_BY_NAME }

